### ISSUE TITLE
Update hexdumps

### ISSUE THREAD

**Issue by thephez** [dash-docs/dash-docs#58]
- [x] Remove non-COutPoint related CTxIn fields (related to #32)
- [x] Add new `mnp` fields (related to #34)
- [x] `mnget` (related to #39)
